import { GraduationCap, LockKey } from "@phosphor-icons/react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { z } from "zod";
import { resetPassword } from "../services/api";
import { Button } from "../components/ui/Button";

const schema = z.object({ password: z.string().min(8, "Mật khẩu cần ít nhất 8 ký tự"), confirm: z.string() }).refine((v) => v.password === v.confirm, { path: ["confirm"], message: "Xác nhận mật khẩu chưa khớp" });
type Form = z.infer<typeof schema>;
export function ResetPassword() { const [params] = useSearchParams(); const navigate = useNavigate(); const token = params.get("token") || ""; const form = useForm<Form>({ resolver: zodResolver(schema) }); const submit = async (v: Form) => { try { await resetPassword(token, v.password); navigate("/login"); } catch (e) { form.setError("root", { message: (e as { response?: { data?: { detail?: string } } }).response?.data?.detail || "Không thể đặt lại mật khẩu." }); } }; const field = "h-11 w-full rounded-lg border border-line pl-10 pr-3 text-sm outline-none focus:border-brand focus:ring-4 focus:ring-green-100"; return <main className="grid min-h-[100dvh] place-items-center bg-canvas px-4"><section className="w-full max-w-md rounded-3xl border border-line bg-white p-8 shadow-[0_18px_45px_rgba(46,125,50,.12)]"><span className="grid size-12 place-items-center rounded-2xl bg-brand text-white"><GraduationCap size={26} weight="fill"/></span><h1 className="mt-5 text-2xl font-bold text-ink">Tạo mật khẩu mới</h1><p className="mt-2 text-sm text-muted">Mật khẩu mới sẽ đăng xuất mọi phiên cũ.</p>{!token ? <p className="mt-6 rounded-lg bg-red-50 p-3 text-sm text-error">Liên kết đặt lại không hợp lệ.</p> : <form className="mt-6 space-y-4" onSubmit={form.handleSubmit(submit)}>{([['password','Mật khẩu mới'],['confirm','Xác nhận mật khẩu mới']] as const).map(([name,label]) => <label key={name} className="block text-sm font-semibold text-ink">{label}<div className="relative mt-2"><LockKey className="absolute left-3 top-3 text-muted" size={18}/><input type="password" className={field} {...form.register(name)}/></div>{form.formState.errors[name] && <span className="mt-1 block text-xs text-error">{form.formState.errors[name]?.message}</span>}</label>)}{form.formState.errors.root && <p className="text-sm text-error">{form.formState.errors.root.message}</p>}<Button className="w-full" type="submit" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting ? "Đang cập nhật..." : "Đặt lại mật khẩu"}</Button></form>}<Link to="/login" className="mt-6 block text-center text-sm font-semibold text-brand">Quay lại đăng nhập</Link></section></main>; }
